config/routes.rb
Alertsmall::Application.routes.draw do
  devise_for :users
  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"

  resources :tweets, :except => :update
  match '/admin', :to => 'tweets#index', :via => [:get]
  match '/tweets/admin_approve' => 'tweets#admin_approve', :as =>'admin_approve', :via => [:patch]
  match '/admins/hit_impressions' => 'admins#hit_impressions', :as =>'impressions', :via => [:get]
  match '/admins/blocked_users' => 'admins#blocked_users', :as =>'banned', :via => [:get]
  match '/admins/user_scores' => 'admins#user_scores', :as =>'user_scores', :via => [:get]
  match '/admins/block' => 'admins#block', :via => [:post]
  match '/admins/text' => 'admins#text', :via => [:get]
  match '/tweets/connect_users' => 'tweets#connect_users', :as=>'connectingyou', :via => [:post]
  match '/tweets/critiquking_reckoner' => 'tweets#critiquking_reckoner', :via => [:post]
  get '/auth/failure'=> 'tweets#new'
  get 'auth/:provider/callback' => 'tweets#new'

  root :to => "tweets#new"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  self.per_page = 10
  is_impressionable
  validates :body, :presence => true
  attr_accessible :body, :provider, :johndoe, :posted, :username

  after_save :update_users_scores
  #before_destroy :take_away_users_score

  protected
  def update_users_scores
    unless UsersScore.where(username: self.username, posted: self.posted).exists?(conditions = :none)
      his_score = UsersScore.new
      his_score.username = self.username
      his_score.posted = self.posted
      his_score.score = 1
      his_score.provider = self.provider
      his_score.save
    else
      existing_user = UsersScore.find_by(username: self.username, posted: self.posted)
      existing_user.score = existing_user.score + 1
      existing_user.save
    end


  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :authenticate_user!, :only => [:index]
  impressionist actions: [:new]
  helper_method :critiquking_reckoner

  def index
    @tweets = Tweet.page(params[:page]).order('created_at DESC')
    respond_to do |format|
      format.html
      format.xml { render :xml => @tweet }
    end
  end

  def new
    session.clear if params["not_johndoe"]
    @username = session[:username]
    @tweet = Tweet.new
  end


  def stitch_split_reviews splitreview
    opinion = splitreview['liked_dish'] == "true" ? "Liked" : "Disliked"
    unless splitreview['review_dishname'].empty? and splitreview['review_placename'].empty?
     stitched_review = "#{opinion} #{splitreview['review_dishname'].titleize} at #{splitreview['review_placename'].titleize}, ##{splitreview['city']}. #{splitreview['review_thoughts']}"
    else
      stitched_review = ""
    end

    return stitched_review
  end

  def create
    foodcops_message = rand(2) == 1 ? "Keep watching our <a href='https://twitter.com/PuneFoodAlerts' target='_blank'>feeds</a>. Thanks!" : "Meanwhile sign-in with twitter & Join the <a href='/admins/user_scores' target='_blank'>LEADERBOARD</a>"
    params[:tweet][:body] = stitch_split_reviews params[:splitreview]
    session[:username] = tweet_params["username"].present? ?  tweet_params["username"] : false

    # WHEN JohnDoe is false
    if request.env['omniauth.auth'].present? or session[:username].present?
      params[:tweet][:provider] = 'twitter'
      params[:tweet][:johndoe] = false
      params[:tweet][:username] = session[:username] || request.env['omniauth.auth']['info']['nickname']
      session[:auth_hash] =  request.env['omniauth.auth']
    else
      params[:tweet][:username] = 'JohnDoe'
    end

    @post_content = formulate_post_content tweet_params["username"], tweet_params["body"]

    want_to_publish? #This is for assigning :posted field to true or false

    @tweet = Tweet.new(params[:tweet])
    respond_to do |format|
      if blocked_user? tweet_params["username"]
        format.html { redirect_to new_tweet_path , alert: "<b><u>YOU ARE BLOCKED ASSHOLE!!</u></b><br/>Contact me to know the reason." }
      else
        unless  validate_tweet_body? @post_content
         format.html { redirect_to new_tweet_path , alert: "<b>IM SORRY!! YOUR PLATE IS FULL</b><br/>Keep your review short & sweet" }
        else
          unless validate_username_count? tweet_params["username"]
            format.html { redirect_to new_tweet_path , alert: "<b><u>SORRY!! NO 2nd HELPING</u></b><br/>Please review as 'Anonymous' or come back tomorrow.<br/> Meanwhile, <a href='#' onclick='focusStayConnected();'>Stay Connected</a> with us" }
        else
          if @tweet.save
            UserMailer.delay.someone_tweeted(@tweet.id)
            publish_tweet @post_content if want_to_publish?
            flash_message_after_review = want_to_publish? ? "<b><u>BULLSEYE!!</u></b><br/>Your review has been posted to the <a href='https://twitter.com/PuneFoodAlerts' target='_blank'>Feeds</a>. <br/> Hope you've already Liked our pages. Thank you" : "<b><u>FOOD COP @ WORK!!</u></b> <br/> Your review is being supervised. Please wait for approval<br/> #{foodcops_message} "
            format.html { redirect_to new_tweet_path, notice: "#{flash_message_after_review}" }
            format.json { render action: 'tweets/new', status: :created, location: @tweet }
          else
            format.html { redirect_to new_tweet_path , alert: "<b><u>YOUR PLATE LOOKS EMPTY!!</u></b><br/>Have you specified the Dish or Restaurant name?" }
          end
         end
        end
        end
    end

  end

  def formulate_post_content username, post_body
    @length_of_via_text = 6 #via(@)
    @skeleton_length = post_body.length + username.length + @length_of_via_text

    case @skeleton_length
      when (133..140)
        @post_script = username == 'JohnDoe' ? '(via www.aFoodie.Me)' : "via(@#{username})"
      when (100..133)
        @post_script = username == 'JohnDoe' ? '(via www.aFoodie.Me)' : "via(#aFoodieMe @#{username})"
      when (0..100)
        @post_script = username == 'JohnDoe' ? '(via www.aFoodie.Me)' : "via(@#{username}) #EveryoneIsAFoodie"
    end

    return @post_content_formulated = "#{post_body} #{@post_script}"
  end


  def want_to_publish?
    if params[:tweet][:username].present? and params[:tweet][:johndoe] == false
      params[:tweet][:posted] = true
      return true
    else
      return false
    end
  end

  def tweet_params
    params.require(:tweet).permit(:body, :username)
  end

  def publish_tweet post_content
    CLIENT.update(post_content)
  end


  def admin_approve
    tweet_id_to_pubish = params["tweet"]["tweet_id"].to_i
    @tweet_details_to_publish = Tweet.find(tweet_id_to_pubish)

    if @tweet_details_to_publish.update(posted: true)
      publish_tweet formulate_post_content @tweet_details_to_publish.username, @tweet_details_to_publish.body
    end
  end

  def connect_users
    params[:connecting][:mobilenumber] = false
    @connected_user = ConnectedUserinfo.new(params[:connecting])
    UserMailer.delay.connecting_users(params[:connecting][:info])
    if @connected_user.save
      render nothing: true
    else
      render nothing: true
    end
  end

  def destroy
    redirect_to new_tweet_path, :flash => { :success => "Destroyed!!" }
  end

  def critiquking_reckoner
    if params[:badge_earned].present?
      UsersScore.update_all(:critiquking => false)
      ck = UsersScore.find_by_username(session[:username])
      ck.critiquking = true
      ck.save
      render nothing: true
    end
    $TOPSCORE_WALL = 2
    if request.env['omniauth.auth'].present? or session[:username].present?
     session[:username] = request.env['omniauth.auth'].present? ? request.env['omniauth.auth']['info']['nickname'] : session[:username]
     @current_user_score = UsersScore.where(username: session[:username]).limit(1).pluck(:score)
     @current_top_score = UsersScore.where("provider <> 'JohnDoe' and critiquking = true").maximum(:score)

     if @current_user_score.present? and @current_top_score.present?
       if @current_user_score[0] > $TOPSCORE_WALL and @current_user_score[0] > @current_top_score and not UsersScore.where(username: session[:username]).exists?(:critiquking => true)
          true
       else
         @current_user_score[0] == @current_top_score + 1 ? true : false
       end
     elsif @current_user_score.present? and @current_user_score[0] == $TOPSCORE_WALL + 1
        true
     else
       false
     end
    else
      false
    end

  end




#VALIDATION METHODS CAN BE SHIFTED TO MODEL. LEARN HOW

  def blocked_user? username
    @blocked_user_records = BlockedUsers.all
    @blocked_usernames = @blocked_user_records.pluck(:username)
    return @blocked_usernames.any?{ |s| s.casecmp(username)==0 }
  end


  def validate_tweet_body? post_content
    if post_content.length > 140
      false
    else
      true
    end
  end

  def validate_username_count? username
    if username == 'JohnDoe'
      true
    else
      if Tweet.where("created_at >= ? AND username='#{username}'", Time.zone.now.beginning_of_day).present?
        false
      else
        true
      end
    end
  end


end

app/helpers/tweets_helper.rb
module TweetsHelper


end

app/views/tweets/_facebook_box.html.erb
<div class="fb-box-vanish">
<div class="fb-like-box" data-href="https://www.facebook.com/www.afoodie.me" data-width="300" data-height="70" data-small-header="true" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/afoodie.me"><a href="https://www.facebook.com/afoodie.me">Everyone Is A Foodie</a></blockquote></div></div>
</div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/tweets/_review_split_input.html.erb
<input type="hidden" name="splitreview[its_anonymous]" id="its_anonymous" value="false">
<div id="infoToggler">
  <img src="/assets/i_Liked_Button.png"  width="50px" height="45px" style="margin-top: 15px;"/>
  <img src="/assets/i_Dislike_Button.png"  width="50px" height="45px" style="display:none; margin-top: 20px;"/>
  <!--<label class="label-for-checkbox" id="disliked_label" style="margin-left: 4px; display: inline;">Liked</label>-->
  <input type="hidden" name="splitreview[liked_dish]" id="liked_dish" value="true">
</div>
<input autocomplete="off" class="review_boxes" id="review_dishname" name="splitreview[review_dishname]" placeholder="Dish  Eg:Pizza" type="text" />
<input autocomplete="off" class="review_boxes" id="review_placename" name="splitreview[review_placename]" placeholder="Restaurant  Eg:BBQ Nation" type="text" />


<div class="styled-select green rounded">
    <select name="splitreview[city]" id="review_city">
      <option value="Pune" selected="selected">Choose City</option>
      <option value="Pune">#Pune</option>
      <option value="Mumbai">#Bombay</option>
    </select>
</div>




<input autocomplete="off" class="review_boxes" id="review_thoughts" name="splitreview[review_thoughts]" placeholder="Other Thoughts..." type="text" />


<style>


    #infoToggler {
        display: inline;
        margin-right: 12px;
    }

    #review_dishname{
        width: 180px;
    }

    #review_thoughts{
        width: 275px;
        text-align:center;
    }

    #review_placename{
        width: 225px;
        text-align:center;
    }

    input.review_boxes
    {
        margin-top: 20px;
        -webkit-appearance: none;
        background: #f5f5f5;
        padding: 0.80em;
        -moz-transition: background-color 0.35s ease-in-out;
        -webkit-transition: background-color 0.35s ease-in-out;
        -o-transition: background-color 0.35s ease-in-out;
        -ms-transition: background-color 0.35s ease-in-out;
        transition: background-color 0.35s ease-in-out;
    }

    input.review_boxes:focus
    {
        background: #f2f2f2;
    }

    @media (max-width: 600px) {
        #review_dishname{
            width: 195px;
        }

        #review_city{
            width: 290px;
        }

        #review_thoughts{
            width: 270px;
        }

        #review_placename{
            width: 270px;
        }

    }



    .styled-select {
        display:inline-block;
        background: url(http://i62.tinypic.com/15xvbd5.png) no-repeat 100% 0;

        height: 40px;
    }

    .styled-select select {
        background: transparent;
        border: none;
        height: 40px;
        padding: 5px; /* If you add too much padding here, the options won't show in IE */
        width: 120px;
        -moz-appearance: none !important;
        /*for chrome*/
        -webkit-appearance:none;
        appearance: none !important;
        border: 0 !important;
    }

    .rounded {
        -webkit-border-radius: 20px;
        -moz-border-radius: 20px;
        border-radius: 20px;
    }

    .green   { background-color: #89AE44; }
    .green select   { color: #fff; }

</style>



<script>

    $(document).ready(function(){
        $("#infoToggler").click(function() {
            $(this).find('img').toggle();
            var hiddenField = $('#liked_dish'),
            val = hiddenField.val();
            hiddenField.val(val === "false" ? "true" : "false");
            $('#disliked_label').text($('#disliked_label').text() == "Liked" ? "Disliked" : "Liked");
            console.log("new value: " + hiddenField.val());
        });
    });
</script>

app/views/tweets/_tweet_feeds.html.erb
<a class="twitter-timeline" href="https://twitter.com/PuneFoodAlerts"  data-widget-id="455255738835673088">@PuneFoodAlerts Tweets</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/tweets/index.html.erb
<h2>MANAGE REVIEWS </h2>

<div id="div-for-tweetlist" >
 <%= will_paginate @posts %>

    <table class="table table-hover">
      <tr>
        <th>SL #</th>
        <th>Content</th>
        <th>Post By?</th>
        <th>Publish</th>
        <th>Delete Review</th>
      </tr>
      <% count = ((params[:page] || 1).to_i - 1) * 10  %>
      <% @tweets.each do |tweet| %>
          <%= form_for(tweet, :url => admin_approve_path, :html => {:multipart => true, :class=> 'tweet-form-inline'}, :remote=>true ) do |t| %>
          <tr>
            <td><%= count %></td>
            <td><%= tweet.body %></td>
            <td><%= tweet.johndoe? ? "JohnDoe" : tweet.username %></td>
            <%= t.hidden_field :tweet_id, :value => tweet.id%>
            <td><%= t.submit "Publish", :class=> 'publish-button' unless tweet.posted? %></td>
          <% end %>
            <%  unless tweet.posted? %>
            <form class="form-inline" action="admins/block" data-remote="true" id="remove_review" method="post">
              <input type="hidden" name="tweetid_to_remove" id="tweet_id" value=<%= tweet.id %>>
              <td><input style="color: #8b0000;" class="btn remove-button" id="remove_review_button" name="remove_review_button" type="submit" value="Remove!" /></td>
            <%else%>
               <td> </td>
            <%end%>
            </form>
          </tr>
          <% count += 1 %>
      <% end %>
    </table>

</div>



<script>

    $("#remove_review_button").click(function () {
        setTimeout(function () { location.reload(1); }, 400);
    });


    $(".publish-button").click(function () {
        setTimeout(function () { location.reload(1); }, 400);
    });

</script>

app/views/tweets/new.html.erb
<%- model_class = Tweet -%>
<% if request.env["omniauth.auth"].present?
     @placeholder_text = "Type review in 140 characters (via @#{request.env["omniauth.auth"]["info"]["nickname"]})...."
     @button_text = "POST REVIEW"
     @should_login = false
   elsif session[:username].present?
     @placeholder_text = "Type review in 140 characters (via @#{session[:username]})...."
     @button_text = "POST REVIEW"
     @should_login = false
   else
     @placeholder_text = "To Review- Please Sign In  OR  Be Anonymous"
     @button_text = "Login"
     @should_login = true
  end
%>

<div class="page-header-new">
  <%= image_tag("pageheader_morningmirror.jpg" ) %>
</div>

<%= form_for @tweet, :html => { :name => 'post-form', :class => 'form-horizontal' } do |f| %>
    <div class="control-group" style="text-align: center;">

      <div id="inner" >
        <div style="display: none;" id="split_review">
            <%= render 'tweets/review_split_input' %>
        </div>
        <div id="fulltext_review">
           <%= f.text_field :body, :class => 'text', :placeholder => "#{@placeholder_text}", :autocomplete => "off" %>
        </div>
        <div class="label-for-checkbox">
          <%if request.env["omniauth.auth"].nil? %>
              <%if @username.present? %>
                  <input type="hidden" id="tweet_username" name="tweet[username]" value=<%= @username%>>
                  <%= link_to "No, Dont Mention @#{@username}. Log Me Out!!", new_tweet_path(not_johndoe: true), class: "anchor-style" %>
              <%else%>
                  <label class="label-for-checkbox">
                  <input id="JohnDoe" class="checkbox" type="checkbox" onclick="handleClick(this);" <%if params[:not_johndoe] %>checked="checked"<%end %>>
                  Be Anonymous
                  </label>
              <%end%>
          <%else%>
              <% @username = request.env["omniauth.auth"]["info"]["nickname"]
                 session[:username] = @username
                 @name = request.env["omniauth.auth"]["info"]["name"]%>
              <%= link_to "Logout! Dont Mention @#{@username}", new_tweet_path(not_johndoe: true)%>
              <input type="hidden" id="tweet_username"  name="tweet[username]" value=<%= request.env["omniauth.auth"]["info"]["nickname"]%>>
          <%end%>
        </div>


          <div class="social-buttons span4 offset4" id="social-buttons">
            <a class="btn btn-twitter btn-block" href="/auth/twitter">Sign in with Twitter</a>
           <!-- <a class="btn btn-facebook btn-block" href="/auth/facebook"><i class="fa fa-facebook"></i>Sign in with Facebook</a>-->
          </div>

            <%= f.submit "#{@button_text}", :class => 'button', :id =>"tweet_or_login" %>


      </div>

    </div>


<% end %>



<div id="myModal" class="modal-dialog modal fade" style="display: none;">
  <div class="modal-content">
    <div class="modal-header" style="text-align: center;">
      <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
      <h3 class="modal-title">Congrats!!</h3>
      <h4>@<%=  @username %> Just Earned A Badge</h4>

    </div>
    <div class="modal-body" style="text-align: center;">

      <img id="scoreboard_icon" style="width: 80px;height: 80px;" src="/assets/CritiquKing_icon_v2.png"/>
    </div>
    <div class="modal-footer">
      <form data-remote="true" action="/tweets/critiquking_reckoner" class="form-horizontal" id="new_connection" method="post" name="connect-form">
        <%= hidden_field_tag :badge_earned, true-%>
        <button id="woohoo" class="btn connect-button btn-success disabled" type="submit">Woohoo!</button>
        <!--<input class="btn btn-success" type="submit" value="Woohoo!" id="submit">-->
      </form>

    </div>
  </div>
</div>



<script>
    <%if request.env["omniauth.auth"].present? or session[:username].present? %>
        $('#social-buttons').hide();
        $('#tweet_or_login').show();
        $('#split_review').show();
        $('#fulltext_review').hide();
    <%else%>
        $('#social-buttons').show();
        $('#tweet_or_login').hide();
    <%end%>


    document['post-form'].action = "/auth/twitter";



    if($('#JohnDoe').is(':checked')){
        $('#tweet_body').show();
        $('#tweet_or_login').show();
        $('#social-buttons').hide();
        $('#split_review').show();
        $('#fulltext_review').hide();
        $('#its_anonymous').val('true');
        document.getElementById("tweet_or_login").value = "POST REVIEW";
        document['post-form'].action = "/tweets";

    }
    else
    {
        $("#tweet_body").attr('disabled',true);
    }

    var loggedin =  document.getElementById('tweet_username');
    if (typeof(loggedin) != 'undefined' && loggedin != null)
    {
        document['post-form'].action = "/tweets";
        $('#tweet_body').show();
        $("#tweet_body").attr('disabled',false);
    }
    else
    {
        $('#tweet_body').fadeIn(10000);

    }

    <% if request.env["omniauth.auth"].present? or session[:username].present? %>
    <% if critiquking_reckoner%>
    $('#myModal').modal({
        backdrop: 'static'
    })
    $("#myModal").modal('show');

    <%end%>
    <%end%>



    $(document).ready(function(){
        $("#woohoo").click(function(){
            $("#myModal").modal('hide'); //hide popup
        });

        if(document.getElementById("JohnDoe").checked == false){
           document['post-form'].action = "/auth/twitter";
       }

    });

    function focusStayConnected() {
        document.getElementById("connect-textbox").focus();
        $('html, body').animate({scrollTop:500},'slow');
        return false;

    }



    function handleClick(JohnDoe) {
        if(JohnDoe.checked){
            $("#tweet_body").attr('disabled',false);
            $('#social-buttons').hide();
            $('#tweet_or_login').show();
            $('#split_review').show();
            $('#fulltext_review').hide();
            $('#its_anonymous').val('true');
            document.getElementById("tweet_or_login").value = "POST REVIEW";
            document['post-form'].action = "/tweets";
        }
        if(JohnDoe.checked == false) {
            $("#tweet_body").attr('disabled',true);
            $('#social-buttons').show();
            $('#tweet_or_login').hide();
            $('#split_review').hide();
            $('#fulltext_review').show();
            $('#its_anonymous').val('false');
            document.getElementById("tweet_body").placeholder = "To Review- Please Sign In  OR  Be Anonymous";
            document.getElementById("tweet_or_login").value = "Login";
            document['post-form'].action = "/auth/twitter";
        }
    }

</script>