config/routes.rb
Alertsmall::Application.routes.draw do
  devise_for :users
  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"

  resources :tweets, :except => :update
  match '/admin', :to => 'tweets#index', :via => [:get]
  match '/tweets/admin_approve' => 'tweets#admin_approve', :as =>'admin_approve', :via => [:patch]
  match '/admins/hit_impressions' => 'admins#hit_impressions', :as =>'impressions', :via => [:get]
  match '/admins/blocked_users' => 'admins#blocked_users', :as =>'banned', :via => [:get]
  match '/admins/user_scores' => 'admins#user_scores', :as =>'user_scores', :via => [:get]
  match '/admins/block' => 'admins#block', :via => [:post]
  match '/admins/text' => 'admins#text', :via => [:get]
  match '/tweets/connect_users' => 'tweets#connect_users', :as=>'connectingyou', :via => [:post]
  match '/tweets/critiquking_reckoner' => 'tweets#critiquking_reckoner', :via => [:post]
  get '/auth/failure'=> 'tweets#new'
  get 'auth/:provider/callback' => 'tweets#new'

  root :to => "tweets#new"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "#EveryoneIsAFoodie - Crowdsourcing Food Reviews" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <script type="text/javascript" src= "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>


    <!-- Load jQuery from Google's CDN -->
    <!-- Load jQuery UI CSS  -->



    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "jquery-1.4.2.min", "rails", "highcharts" %>


    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <p class="brand" >
            <a href="/">
             <img id="website_brand_icon" src="/assets/everyoneisafoodie.png"/>
            </a>
            <a href="<%=user_scores_path%>">
              <%= image_tag('review_icon.png', size: "30x30", :style => "padding-left:10px")%>

            </a>

          <div id="social_icons" style="float: right; margin-top: 8px;">
              <a href="https://facebook.com/aFoodie.Me" target="_blank">
                <img id="fb" src="/assets/facebooka.png" onmouseover="this.src='/assets/facebook.png'" onmouseout="this.src='/assets/facebooka.png'"/>
              </a>
              <a href="https://twitter.com/PuneFoodAlerts/status/419190747238117376/photo/1" target="_blank" class="social">
                <img id="tw" src="/assets/twittera.png" onmouseover="this.src='/assets/twitter.png'" onmouseout="this.src='/assets/twittera.png'"/>
              </a>
          </div>

          <% if user_signed_in?  %>
          <ol class="breadcrumb" style="padding: 20px;">
            <li>   <%= link_to "User Reviews", admin_path, :class => 'navbar-link'  %></li> /
            <li>   <%= link_to "User Impressions", impressions_path, :class => 'navbar-link'  %></li> /
            <li>   <%= link_to "Blocked Users", banned_path, :class => 'navbar-link'  %></li> /
            <li>   <%= link_to "Users Score", user_scores_path, :class => 'navbar-link'  %></li> /
            <li>   <%= link_to "Text", admins_text_path, :class => 'navbar-link'  %></li>
          </ol>
          <%end%>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9" style="width: 100%;">
            <%= bootstrap_flash %>
             <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                  <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                  <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </p>
            <%= yield %>
          </div>

        </div><!--/row-->
    </div> <!-- /container -->

    <div id="push"></div>
      <div id="footer">
        <%= render 'tweets/tweet_feeds' %>
        <%= render 'tweets/facebook_box'%>  <br/>
        <div class="footer-container">
          <p>&copy; #EveryoneIsAFoodie<br/></p><p > Website by <a href="http://www.twitter.com/HandleChanger" target="_blank" class="anchor-style">Johnny</a> in <a href="http://rubyonrails.org/" target="_blank" class="anchor-style">RoR</a></p>
        </div>
        <div id="twitter-box-vanish"  style="float: left; margin-left: 4.5%; margin-top: 4%;">
          <a href="https://twitter.com/PuneFoodAlerts" class="twitter-follow-button" data-show-count="false" data-dnt="true">Follow @PuneFoodAlerts</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        </div>
        <div class="stay-connected-form">
          <p class="connect-text"><b>STAY CONNECTED</b></p>
          <form data-remote="true" action="/tweets/connect_users" class="form-horizontal" id="new_connection" method="post" name="connect-form">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <input style="padding: 0.5em;" id="connect-textbox" class="connect-text-box" type="email" name="connecting[info]" placeholder="Enter your e-mail">
            <button style=" padding-bottom: 7px;" id="connect-id" class="btn connect-button btn-success disabled" type="submit"><i class="icon-large icon-white icon-envelope"></i></button>
            <img style="display: none; height: 16px; width: 16px;" id="connect-loading" src="/assets/green-loading.gif" onmouseover="this.src='/assets/twitter.png'" onmouseout="this.src='/assets/twittera.png'"/>
            <span style="display: none;" id="afterconnect-message" class="label label-success">THANK YOU! WE'LL KEEP YOU POSTED</span>
           </form>
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <!-- afoodie.me -->
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-8833339331238063"
               data-ad-slot="6883757234"
               data-ad-format="auto"></ins>
          <script>
              (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
           </span>
          </p>
        </div>
      </div>

  </body>

<script>
    $('#connect-id').click(function(){
        $('#connect-loading').show();
        $('#connect-id').hide();
        $.ajax({
            success:function(result){
            $('#connect-loading').hide();
            $('#connect-textbox').hide();
            $('#afterconnect-message').show();
           }
        })
    })

</script>

</html>